-- CreateTable
CREATE TABLE `tbl_aggiunto_in` (
    `ID_PRODOTTO` VARCHAR(50) NOT NULL,
    `ID_CARRELLO` VARCHAR(50) NOT NULL,

    INDEX `ID_CARRELLO`(`ID_CARRELLO`),
    INDEX `ID_PRODOTTO`(`ID_PRODOTTO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tbl_carrello` (
    `ID` VARCHAR(50) NOT NULL,
    `DATA_ACQUISTO` DATE NULL,
    `QUANTITA_PRODOTTO` INTEGER NOT NULL,
    `PREZZO_TOTALE` FLOAT NOT NULL,
    `EMAIL_CLIENTE` VARCHAR(50) NULL,

    INDEX `EMAIL_CLIENTE`(`EMAIL_CLIENTE`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tbl_cliente` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NOME` VARCHAR(50) NOT NULL,
    `COGNOME` VARCHAR(50) NOT NULL,
    `EMAIL` VARCHAR(50) NOT NULL,
    `CELLULARE` VARCHAR(50) NOT NULL,
    `CODICE_FISCALE` VARCHAR(50) NOT NULL,
    `DATA_DI_NASCITA` VARCHAR(50) NOT NULL,
    `CITTA` VARCHAR(50) NOT NULL,
    `VIA` VARCHAR(50) NOT NULL,
    `N_CIVICO` VARCHAR(50) NOT NULL,
    `CAP` VARCHAR(50) NOT NULL,
    `NUM_CARTA` VARCHAR(50) NOT NULL,
    `CVV_CARTA` VARCHAR(50) NOT NULL,
    `INTESTATARIO_CARTA` VARCHAR(50) NULL,
    `SCADENZA_CARTA` DATE NULL,
    `RUOLO` VARCHAR(50) NULL DEFAULT 'cliente',
    `UTENTE_PASSWORD` VARCHAR(50) NULL DEFAULT '1',

    UNIQUE INDEX `EMAIL`(`EMAIL`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tbl_corriere` (
    `P_IVA` VARCHAR(50) NOT NULL,
    `NOME` VARCHAR(30) NOT NULL,
    `TELEFONO` VARCHAR(50) NOT NULL,
    `EMAIL` VARCHAR(30) NOT NULL,

    PRIMARY KEY (`P_IVA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tbl_dipendente` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `NOME` VARCHAR(50) NOT NULL,
    `COGNOME` VARCHAR(50) NOT NULL,
    `EMAIL` VARCHAR(50) NOT NULL,
    `VIA` VARCHAR(50) NOT NULL,
    `N_CIVICO` VARCHAR(50) NOT NULL,
    `CAP` VARCHAR(50) NOT NULL,
    `CITTA` VARCHAR(50) NOT NULL,
    `CODICE_FISCALE` VARCHAR(50) NOT NULL,
    `DATA_DI_NASCITA` VARCHAR(50) NOT NULL,
    `DATA_ASSUNZIONE` DATE NULL,
    `PAGA_ORARIA` FLOAT NOT NULL,
    `CODICE_ZONA` VARCHAR(50) NULL,
    `RUOLO` VARCHAR(50) NULL DEFAULT 'dipendente',
    `UTENTE_PASSWORD` VARCHAR(50) NULL DEFAULT '1',

    INDEX `CODICE_ZONA`(`CODICE_ZONA`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tbl_emette_spedizione` (
    `CODICE_ZONA_FILIALE` VARCHAR(50) NOT NULL,
    `NUMERO_TRACCIAMENTO` VARCHAR(50) NOT NULL,

    INDEX `CODICE_ZONA_FILIALE`(`CODICE_ZONA_FILIALE`),
    INDEX `NUMERO_TRACCIAMENTO`(`NUMERO_TRACCIAMENTO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tbl_filiale` (
    `NOME_FILIALE` VARCHAR(50) NOT NULL,
    `SEDE` VARCHAR(50) NOT NULL,
    `CODICE_ZONA_FILIALE` VARCHAR(50) NOT NULL,

    PRIMARY KEY (`CODICE_ZONA_FILIALE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tbl_fornitore` (
    `P_IVA` VARCHAR(11) NOT NULL,
    `NOME` VARCHAR(50) NOT NULL,
    `CITTA` VARCHAR(30) NOT NULL,
    `VIA` VARCHAR(30) NOT NULL,
    `CAP` VARCHAR(30) NOT NULL,

    PRIMARY KEY (`P_IVA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tbl_fornitura` (
    `ID_FORNITURA` VARCHAR(50) NOT NULL,
    `P_IVA` VARCHAR(50) NOT NULL,
    `CODICE_ZONA` VARCHAR(50) NOT NULL,
    `PREZZO` FLOAT NULL,
    `DATA_ACQUISTO` DATE NULL,
    `DATA_SPEDIZIONE` DATE NULL,

    INDEX `P_IVA`(`P_IVA`),
    PRIMARY KEY (`ID_FORNITURA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tbl_gestito_da` (
    `ID_FILIALE` VARCHAR(50) NOT NULL,
    `CODICE_ORDINE` VARCHAR(50) NOT NULL,

    INDEX `CODICE_ORDINE`(`CODICE_ORDINE`),
    INDEX `ID_FILIALE`(`ID_FILIALE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tbl_magazzino` (
    `CODICE_MAGAZZINO` VARCHAR(50) NOT NULL,
    `ID_PRODOTTO` VARCHAR(50) NOT NULL,
    `QUANTITA_PRODOTTO` INTEGER NOT NULL,
    `NOME_PRODOTTO` VARCHAR(51) NULL,
    `NOME_MAGAZZINO` VARCHAR(50) NULL,

    INDEX `CODICE_MAGAZZINO`(`CODICE_MAGAZZINO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tbl_ordine` (
    `ID_ORDINE` VARCHAR(50) NOT NULL,
    `FATTURA` VARCHAR(50) NOT NULL,
    `NUMERO_ORDINE` INTEGER NULL,
    `ID_CARRELLO` VARCHAR(50) NULL,
    `INDIRIZZO_SPEDIZIONE` VARCHAR(50) NULL,
    `STATO_ORDINE` VARCHAR(50) NULL DEFAULT 'non gestito',

    INDEX `ID_CARRELLO`(`ID_CARRELLO`),
    PRIMARY KEY (`ID_ORDINE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tbl_prodotto` (
    `NOME_PRODOTTO` VARCHAR(50) NOT NULL,
    `PREZZO_PRODOTTO` FLOAT NOT NULL,
    `QUANTITA` INTEGER NOT NULL,
    `PROVENIENZA` VARCHAR(50) NOT NULL,
    `ID_FORNITURA` VARCHAR(50) NOT NULL,
    `ID_PRODOTTO` VARCHAR(50) NOT NULL,

    INDEX `ID_FORNITURA`(`ID_FORNITURA`),
    PRIMARY KEY (`ID_PRODOTTO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tbl_spedizione` (
    `NUMERO_TRACCIAMENTO` VARCHAR(50) NOT NULL,
    `P_IVA_CORRIERE` VARCHAR(50) NOT NULL,
    `NUMERO_ORDINE` VARCHAR(50) NOT NULL,
    `DATA_PARTENZA` DATE NOT NULL,
    `DATA_ARRIVO` DATE NOT NULL,

    INDEX `P_IVA_CORRIERE`(`P_IVA_CORRIERE`),
    PRIMARY KEY (`NUMERO_TRACCIAMENTO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `tbl_aggiunto_in` ADD CONSTRAINT `tbl_aggiunto_in_ibfk_1` FOREIGN KEY (`ID_PRODOTTO`) REFERENCES `tbl_prodotto`(`ID_PRODOTTO`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `tbl_aggiunto_in` ADD CONSTRAINT `tbl_aggiunto_in_ibfk_2` FOREIGN KEY (`ID_CARRELLO`) REFERENCES `tbl_carrello`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `tbl_carrello` ADD CONSTRAINT `tbl_carrello_ibfk_1` FOREIGN KEY (`EMAIL_CLIENTE`) REFERENCES `tbl_cliente`(`EMAIL`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `tbl_dipendente` ADD CONSTRAINT `tbl_dipendente_ibfk_1` FOREIGN KEY (`CODICE_ZONA`) REFERENCES `tbl_filiale`(`CODICE_ZONA_FILIALE`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `tbl_emette_spedizione` ADD CONSTRAINT `tbl_emette_spedizione_ibfk_1` FOREIGN KEY (`CODICE_ZONA_FILIALE`) REFERENCES `tbl_filiale`(`CODICE_ZONA_FILIALE`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `tbl_emette_spedizione` ADD CONSTRAINT `tbl_emette_spedizione_ibfk_2` FOREIGN KEY (`NUMERO_TRACCIAMENTO`) REFERENCES `tbl_spedizione`(`NUMERO_TRACCIAMENTO`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `tbl_fornitura` ADD CONSTRAINT `tbl_fornitura_ibfk_1` FOREIGN KEY (`P_IVA`) REFERENCES `tbl_fornitore`(`P_IVA`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `tbl_gestito_da` ADD CONSTRAINT `tbl_gestito_da_ibfk_1` FOREIGN KEY (`ID_FILIALE`) REFERENCES `tbl_filiale`(`CODICE_ZONA_FILIALE`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `tbl_gestito_da` ADD CONSTRAINT `tbl_gestito_da_ibfk_2` FOREIGN KEY (`CODICE_ORDINE`) REFERENCES `tbl_ordine`(`ID_ORDINE`) ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `tbl_magazzino` ADD CONSTRAINT `tbl_magazzino_ibfk_1` FOREIGN KEY (`CODICE_MAGAZZINO`) REFERENCES `tbl_filiale`(`CODICE_ZONA_FILIALE`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `tbl_ordine` ADD CONSTRAINT `tbl_ordine_ibfk_1` FOREIGN KEY (`ID_CARRELLO`) REFERENCES `tbl_carrello`(`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `tbl_prodotto` ADD CONSTRAINT `tbl_prodotto_ibfk_1` FOREIGN KEY (`ID_FORNITURA`) REFERENCES `tbl_fornitura`(`ID_FORNITURA`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `tbl_spedizione` ADD CONSTRAINT `tbl_spedizione_ibfk_1` FOREIGN KEY (`P_IVA_CORRIERE`) REFERENCES `tbl_corriere`(`P_IVA`) ON DELETE NO ACTION ON UPDATE NO ACTION;
