# Usa un'immagine leggera di un server web
FROM nginx:alpine

# Copia il contenuto del folder frontend nella directory di default di Nginx
COPY . /usr/share/nginx/html

# Esponi la porta 80
EXPOSE 80

# Comando di avvio del server Nginx
CMD ["nginx", "-g", "daemon off;"]
