apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodeserver
          image: daevel/nodejsapp:latest
          env:
            - name: DATABASE_URL
              value: "mysql://root:PQRSK59LQ???@@@@mysql-service:3306/esempio_database"
          ports:
            - containerPort: 3000
