version: '3.8'

services:
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - app

  app:
    build:
      context: backend/
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - '/app/node_modules'
    depends_on:
      - mysql_server

  mysql_server:
    build:
      context: db/
      dockerfile: Dockerfile.database
    environment:
      - MYSQL_DATABASE=experia_coffee
      - MYSQL_USER=daevel
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password