version: '3.8'

services:
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - app
      - mysql_server

  app:
    build:
      context: backend/
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - '/app/node_modules'
    depends_on:
      - mysql_server

  mysql_server:
    build:
      context: db/
      dockerfile: Dockerfile.database
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PWD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PWD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: