apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-deployment
  template:
    metadata:
      name: mysql-deployment
      labels:
        app: mysql-deployment
    spec:
      containers:
        - name: mysql-deployment
          image: daevel/databaseapp:latest
          imagePullPolicy: Always
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: PQRSK59LQ???@@@
            - name: MYSQL_DATABASE
              value: esempio_database
            - name: MYSQL_USER
              value: ""
            - name: MYSQL_PASSWORD
              value: PQRSK59LQ???@@@
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-persistent-storage
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
